[green_agent]
agentbeats_id = "019b4d06-1da3-7c22-88fa-f4660061a779"
env = { LOG_LEVEL = "INFO", OPENAI_API_KEY = "${OPENAI_API_KEY}" }

[[participants]]
name = "agent"
agentbeats_id = "019cb5e7-e77e-71b1-82d5-41516465fa92"
env = { LOG_LEVEL = "INFO", OPENAI_API_KEY = "${OPENAI_API_KEY}", DEEPSEEK_API_KEY = "${DEEPSEEK_API_KEY}", KIMI_API_KEY = "${KIMI_API_KEY}", MINIMAX_API_KEY = "${MINIMAX_API_KEY}", OPENROUTER_API_KEY = "${OPENROUTER_API_KEY}", FEATHERLESS_API_KEY = "${FEATHERLESS_API_KEY}", GOOGLE_API_KEY = "${GOOGLE_API_KEY}", SERPAPI_KEY = "${SERPAPI_KEY}" }

[config]
domain = "airline"
user_llm = "openai/gpt-4o-mini"
